- name: generate base settings
  blockinfile:
    destfile: "{{zookeeper_config_dir}}/zookeeper.properties"
    create: yes
    marker: "<!-- {mark} CLUSTER CONFIG -->"
    block: |
      dataDir={{dataDir}}
      clientPort={{clientPort}}
      initLimit=5
      syncLimit=2
      server.0={{server0}}
      server.1={{server1}}
      server.2={{server2}}
      autopurge.snapRetainCount=3
      autopurge.purgeInterval=24
      tickTime=2000

- name: create zk myid file
  lineinfile:
    destfile: "{{dataDir}}/myid"
    create: yes
    line: "{{myid}}"
