---
- name: Add Super Users list to Kafka Controller Properties
  set_fact:
    kafka_controller_final_properties: "{{ hostvars[controller_host]['kafka_controller_final_properties'] | combine(
      {
          'super.users': hostvars[controller_host]['super_users'] + ';' + hostvars[groups.kafka_broker[0]]['kafka_broker_principal']
      }
    ) }}"

- name: Create Kafka Controller Config
  include_role:
    name: kafka_controller
    tasks_from: create_config.yml
