---
- name: broker group
  group:
    name: "{{ kafka.broker.group }}"
  become: yes

- name: broker user
  user:
    name: "{{ kafka.broker.user }}"
    comment: "Kafka User"
    system: yes
    group: "{{ kafka.broker.group }}"
  become: yes

- name: create broker data directories
  file:
    path: "{{ item }}"
    owner: "{{ kafka.broker.user }}"
    group: "{{ kafka.broker.group }}"
    state: directory
    mode: 0755
  loop: "{{ kafka.broker.datadir }}"
  become: yes

- name: broker plaintext config
  template:
    src: kafka-broker/server.properties.j2
    dest: "{{ kafka.broker.config_file }}"
    mode: 0640
    owner: "{{ kafka.broker.user }}"
    group: "{{ kafka.broker.group }}"
  notify:
    - restart kafka
  become: yes

- name: broker configure service
  systemd:
    name: "{{ kafka.broker.service_name }}"
    enabled: "{{ kafka.broker.systemd.enabled }}"
    state: "{{ kafka.broker.systemd.state }}"
  become: yes
