---
### Installs Confluent Platform Cluster on Oracle Linux 8.
### RBAC enabled.
### MTLS enabled.
### Kafka Broker Customer Listener.
### SSO authentication using OIDC in Control center using Okta IdP

driver:
  name: docker
platforms:
  - name: ${KRAFT_CONTROLLER:-zookeeper}1
    hostname: ${KRAFT_CONTROLLER:-zookeeper}1.confluent
    groups:
      - ${CONTROLLER_HOSTGROUP:-zookeeper}
      - ${CONTROLLER_HOSTGROUP:-zookeeper}_migration
    image: oraclelinux:8-slim
    dockerfile: ../Dockerfile-rhel-java8.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  # - name: ${KRAFT_CONTROLLER:-zookeeper}2
  #   hostname: ${KRAFT_CONTROLLER:-zookeeper}2.confluent
  #   groups:
  #     - ${CONTROLLER_HOSTGROUP:-zookeeper}
  #     - ${CONTROLLER_HOSTGROUP:-zookeeper}_migration
  #   image: oraclelinux:8-slim
  #   dockerfile: ../Dockerfile-rhel-java8.j2
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   networks:
  #     - name: confluent
  # - name: ${KRAFT_CONTROLLER:-zookeeper}3
  #   hostname: ${KRAFT_CONTROLLER:-zookeeper}3.confluent
  #   groups:
  #     - ${CONTROLLER_HOSTGROUP:-zookeeper}
  #     - ${CONTROLLER_HOSTGROUP:-zookeeper}_migration
  #   image: oraclelinux:8-slim
  #   dockerfile: ../Dockerfile-rhel-java8.j2
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   networks:
  #     - name: confluent
  - name: kafka-broker1
    hostname: kafka-broker1.confluent
    groups:
      - kafka_broker
      - kafka_broker_migration
    image: oraclelinux:8-slim
    dockerfile: ../Dockerfile-rhel-java8.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  # - name: kafka-broker2
  #   hostname: kafka-broker2.confluent
  #   groups:
  #     - kafka_broker
  #     - kafka_broker_migration
  #   image: oraclelinux:8-slim
  #   dockerfile: ../Dockerfile-rhel-java8.j2
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   networks:
  #     - name: confluent
  # - name: kafka-broker3
  #   hostname: kafka-broker3.confluent
  #   groups:
  #     - kafka_broker
  #     - kafka_broker_migration
  #   image: oraclelinux:8-slim
  #   dockerfile: ../Dockerfile-rhel-java8.j2
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   networks:
  #     - name: confluent
  - name: schema-registry1
    hostname: schema-registry1.confluent
    groups:
      - schema_registry
      - schema_registry_migration
    image: oraclelinux:8-slim
    dockerfile: ../Dockerfile-rhel-java8.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  # - name: kafka-rest1
  #   hostname: kafka-rest1.confluent
  #   groups:
  #     - kafka_rest
  #     - kafka_rest_migration
  #   image: oraclelinux:8-slim
  #   dockerfile: ../Dockerfile-rhel-java8.j2
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   networks:
  #     - name: confluent
  # - name: kafka-connect1
  #   hostname: kafka-connect1.confluent
  #   groups:
  #     - kafka_connect
  #     - kafka_connect_migration
  #   image: oraclelinux:8-slim
  #   dockerfile: ../Dockerfile-rhel-java8.j2
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   networks:
  #     - name: confluent
  # - name: ksql1
  #   hostname: ksql1.confluent
  #   groups:
  #     - ksql
  #     - ksql_migration
  #   image: oraclelinux:8-slim
  #   dockerfile: ../Dockerfile-rhel-java8.j2
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   networks:
  #     - name: confluent
  # - name: control-center1
  #   hostname: control-center1.confluent
  #   groups:
  #     - control_center
  #     - control_center_migration
  #   image: oraclelinux:8-slim
  #   dockerfile: ../Dockerfile-rhel-java8.j2
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   published_ports:
  #     - "9021:9021"
  #   networks:
  #     - name: confluent
    # Cluster 2 (Kraft) goups, groupnames will be changed during converge phase
  # - name: controller1-mig
  #   hostname: controller1-mig.confluent
  #   groups:
  #     - kafka_controller_migration
  #   image: oraclelinux:8-slim
  #   dockerfile: ../Dockerfile-rhel-java8.j2
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   networks:
  #     - name: confluent
  # - name: controller2-mig
  #   hostname: controller2-mig.confluent
  #   groups:
  #     - kafka_controller_migration
  #   image: oraclelinux:8-slim
  #   dockerfile: ../Dockerfile-rhel-java8.j2
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   networks:
  #     - name: confluent
  # - name: controller3-mig
  #   hostname: controller3-mig.confluent
  #   groups:
  #     - kafka_controller_migration
  #   image: oraclelinux:8-slim
  #   dockerfile: ../Dockerfile-rhel-java8.j2
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   networks:
  #     - name: confluent
provisioner:
  playbooks:
    converge: ${MIGRATION_CONVERGE:-../collections_converge.yml}
  inventory:
    group_vars:
      all:
        confluent_package_version: 7.7.0-0
        confluent_full_package_version: 7.7.0-0.1.0
        confluent_common_repository_baseurl: https://jenkins-confluent-packages.s3.us-west-2.amazonaws.com/7.7.x/21
        sasl_protocol: plain

        rbac_enabled: true

        kafka_broker_custom_listeners:
          client_listener:
            name: CLIENT
            port: 9093

        oauth_enabled: true
        oauth_client_id: ${OAUTH_CLIENT:-user}
        oauth_client_password: ${OAUTH_PASSWORD:-password}
        oauth_groups_scope: groups
        oauth_groups_claim: groups
        oauth_token_uri: https://dev-59009577.okta.com/oauth2/aus96p2og3u7Cpwu65d7/v1/token
        oauth_issuer_url: https://dev-59009577.okta.com/oauth2/aus96p2og3u7Cpwu65d7
        oauth_jwks_uri: https://dev-59009577.okta.com/oauth2/aus96p2og3u7Cpwu65d7/v1/keys
        oauth_expected_audience: Confluent,api://default,https://my-company.com
        schema_registry_oauth_user: ${OAUTH_CLIENT:-sruser}
        schema_registry_oauth_password: ${OAUTH_PASSWORD:-password}
