---
### Installation of Confluent Platform on RHEL9.
### SASL Plain enabled.
### Control Plane listener enabled.
### Kafka Connect Confluent Hub Plugins logic (Installs jcustenborder/kafka-connect-spooldir:2.0.43).
### Custom Service Unit overrides.
### Custom log4j appender names.

driver:
  name: docker
platforms:
  - name: oauth_server
    hostname: oauth.confluent
    groups:
      - oauth_server
    image: quay.io/keycloak/keycloak:latest
    env:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    dockerfile: ../Dockerfile-oauth.j2
    published_ports:
      - "8080:8080"
    command: start-dev
    cgroupns_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    networks:
      - name: confluent
provisioner:
  playbooks:
    converge: prepare.yml
    # converge: ../collections_converge.yml
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
        oauth_enabled: true
        schema_registry_oauth_enabled: false # to test disabling OAuth on one component on a non rbac cluster
        oauth_client_id: ${OKTA_CLIENT:-user}
        oauth_client_password: ${OKTA_PASSWORD:-password}
        oauth_groups_scope: groups
        oauth_groups_claim: groups
        oauth_token_uri: https://dev-59009577.okta.com/oauth2/aus96p2og3u7Cpwu65d7/v1/token
        oauth_issuer_url: https://dev-59009577.okta.com/oauth2/aus96p2og3u7Cpwu65d7
        oauth_jwks_uri: https://dev-59009577.okta.com/oauth2/aus96p2og3u7Cpwu65d7/v1/keys
        oauth_expected_audience: Confluent,api://default,https://my-company.com
        schema_registry_oauth_user: ${OKTA_CLIENT:-sruser}
        schema_registry_oauth_password: ${OKTA_PASSWORD:-password}
