#- name: Download tarball
#  get_url:
#    url="http://packages.confluent.io/archive/{{cp_major_version}}.{{cp_minor_version}}/confluent-{{cp_major_version}}.{{cp_minor_version}}.{{cp_fix_version}}-2.11.tar.gz"
#    dest="/tmp/confluent-{{cp_major_version}}.{{cp_minor_version}}.{{cp_fix_version}}-2.11.tar.gz"
#  register: new_archive

- name: Ensure install location exists
  file:
    path: "{{install_dir}}"
    state: directory
    owner: "{{install_user}}"
    group: "{{install_user}}"

- name: Install tarball
  unarchive:
    src="/tmp/confluent-{{cp_major_version}}.{{cp_minor_version}}.{{cp_fix_version}}-2.11.tar.gz"
    dest="{{install_dir}}"
    copy=no

