---
- name: Verify
  hosts: all
  tasks:

# - name: Copy in Keytab File
#   copy:
#     src: "{{kerberos_keytab_path}}"
#     dest: "{{kerberos.keytab_dir}}/{{kerberos_keytab_path | basename}}"
#     owner: "{{kerberos_user}}"
#     group: "{{kerberos_group}}"
#     mode: '600'
#   notify: "{{kerberos_handler}}"


    - name: Get stats on jolokia jar
      stat:
        path: /opt/jolokia/jolokia.jar
      register: jolokia_jar

    - name: Get stats on prometheus jar
      stat:
        path: /opt/prometheus/jmx_prometheus_javaagent.jar
      register: prometheus_jar

    - name: Get stats on custom repofile
      stat:
        path: /etc/yum.repos.d/custom-confluent.repo
      register: custom_repofile

    - name: Assert files exist properly
      assert:
        that:
          - jolokia_jar.stat.exists
          - not prometheus_jar.stat.exists
          - not custom_repofile.stat.exists
        quiet: yes
