---
- name: Verify
  hosts: all
  tasks:
    - name: Get stats on keytab file
      stat:
        path: /etc/security/keytabs/custom.keytab
      register: keytab

    - name: Assert ownership of keytab file
      assert:
        that:
          - keytab.stat.gr_name == "root"
          - keytab.stat.pw_name == "root"
        quiet: yes

    - name: Check line in krb5.conf
      shell: grep -Fxq "  admin_server = kerberos1:749" /etc/krb5.conf
      register: checkline
      check_mode: no
      changed_when: no
      failed_when: checkline.rc != 0
