- name: 
  hosts: all
  vars:
    cp_major_version: 3
    cp_minor_version: 3
    cp_fix_version: 1
    install_dir: /tmp/confluent
    install_user: vagrant
  roles:
    - cp-install
  strategy: free
