---
- name: Generate CA for Self Signed Certs
  hosts: zookeeper[0]
  gather_facts: no
  tags: certificate_authority
  tasks:
  - import_role:
      name: confluent.variables_handlers
  - name: Create Certificate Authority and Copy to Ansible Host
    include_tasks: tasks/certificate_authority.yml
    when:
      - self_signed|bool
      - regenerate_ca|bool
      - ssl_enabled|bool
