all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: vagrant
    ansible_become: true
zookeeper:
  hosts:
    127.0.0.1:2222:
broker:
  hosts:
    127.0.0.1:2222:
      kafka:
        broker:
          id: 1
connect-distributed:
  hosts:
    127.0.0.1:2222:
schema-registry:
  hosts:
    127.0.0.1:2222:
control-center:
  hosts:
    127.0.0.1:2222:
