- name: create ssl certificate directory on remote machines
  file:
    path: /var/ssl/private
    state: directory
    mode: 0755
- name: pull out cert gen script
  synchronize:
    src: scripts/
    dest: /tmp/scripts
  delegate_to: localhost
- name: create ssl certs
  command: /tmp/scripts/certs-create.sh
  args:
    chdir: /var/ssl/private
  run_once: true
