all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ec2-user
    ansible_become: true
    security_mode: ssl_customcerts
preflight:
  hosts:
    ip-172-31-46-27.us-east-2.compute.internal:
    ip-172-31-37-66.us-east-2.compute.internal:
    ip-172-31-37-219.us-east-2.compute.internal:
    ip-172-31-34-64.us-east-2.compute.internal:
ssl_CA:
  hosts:
    ip-172-31-34-64.us-east-2.compute.internal:
zookeeper:
  hosts:
    ip-172-31-46-27.us-east-2.compute.internal:
    ip-172-31-37-66.us-east-2.compute.internal:
    ip-172-31-37-219.us-east-2.compute.internal:
broker:
  hosts:
    ip-172-31-46-27.us-east-2.compute.internal:
      kafka:
        broker:
          id: 1
    ip-172-31-37-66.us-east-2.compute.internal:
      kafka:
        broker:
          id: 2
    ip-172-31-37-219.us-east-2.compute.internal:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    ip-172-31-46-27.us-east-2.compute.internal:
control-center:
  hosts:
    ip-172-31-37-66.us-east-2.compute.internal:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: ip-172-31-46-27.us-east-2.compute.internal:8083
connect-distributed:
  hosts:
    ip-172-31-46-27.us-east-2.compute.internal:
kafka-rest:
  hosts:
    ip-172-31-46-27.us-east-2.compute.internal:
ksql:
  hosts:
    ip-172-31-37-66.us-east-2.compute.internal:
tools:
  hosts:
    ip-10-0-0-180.us-east-2.compute.internal:
