zookeeper:
  config:
    clientPort: 2181
broker:
  config:
    port: 9092
confluent:
  package_name: confluent-platform-2.11
  repository:
    debian:
    redhat:
      main:
        baseurl: https://s3-us-west-2.amazonaws.com/jenkins-confluent-packages/4.1.x/97/rpm/4.1
        gpgcheck: 0
        gpgkey: https://s3-us-west-2.amazonaws.com/jenkins-confluent-packages/4.1.x/97/rpm/4.1/archive.key
        enabled: 1
      dist:
        baseurl: https://s3-us-west-2.amazonaws.com/jenkins-confluent-packages/4.1.x/97/rpm/4.1/7
        gpgcheck: 0
        gpgkey:  https://s3-us-west-2.amazonaws.com/jenkins-confluent-packages/4.1.x/97/rpm/4.1/archive.key
        enabled: 1
