---
- name: Zookeeper Provisioning
  hosts: zookeeper
  tasks:
    - include_role:
        name: confluent.zookeeper

- name: Kafka Broker Provisioning
  hosts: kafka_broker
  tasks:
    - include_role:
        name: confluent.kafka_broker
