---
- name: control center create group
  group:
    name: "{{ confluent.control.center.group }}"
  become: yes

- name: control center create user
  user:
    name: "{{ confluent.control.center.user }}"
    comment: "Control Center User"
    system: yes
    group: "{{ confluent.control.center.group }}"
  become: yes

- name: control center create config
  template:
    src: control-center/control-center.properties.j2
    dest: "{{ confluent.control.center.config_file }}"
    mode: 0640
    owner: "{{ confluent.control.center.user }}"
    group: "{{ confluent.control.center.group }}"
  notify:
    - restart control center
  become: yes

- name: control center configure service
  systemd:
    name: "{{ confluent.control.center.service_name }}"
    enabled: "{{ confluent.control.center.systemd.enabled }}"
    state: "{{ confluent.control.center.systemd.state }}"
  become: yes
