---
- set_fact:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

- name: Create Backup Folders
  file:
    path: "{{ backup_location }}/{{ item | dirname }}"
    state: directory
    mode: 0640
  loop: "{{ backup_files }}"

- name: Backup Configuration files
  copy:
    src: "{{ item }}"
    remote_src: yes
    dest: "{{ backup_location }}/{{ item }}-{{timestamp}}"
  loop: "{{ backup_files }}"

- name: Put back configuration
  copy:
    dest: "{{ item }}"
    remote_src: yes
    src: "{{ backup_location }}/{{ item }}-{{timestamp}}"
  loop: "{{ backup_files }}"
