---
- name: Get Controller Broker ID
  shell: |
    {{ binary_base_path }}/bin/zookeeper-shell {{ groups['zookeeper'][0] }}:{{zookeeper_client_port}} \
      {% if zookeeper_ssl_enabled|bool %}--zk-tls-config-file {{kafka_broker.config_file}}{% endif %} \
      get /controller | grep brokerid
  register: controller_query
  run_once: true
  changed_when: false
  check_mode: false

- set_fact:
    controller_json: "{{controller_query.stdout}}"
    broker_id: "{{kafka_broker_final_properties['broker.id']}}"

- debug:
    msg: "Broker ID: {{broker_id}} and Controller ID: {{controller_json.brokerid}}"

# All kafka_broker hosts iterate over the list of kafka_broker hosts, each seeing the list in the same order
# At one given loop entry, only one host will have its inventory_hostname match the entry in the loop
# <ordered_action_tasks> tasks will only run for that host ON that host
- name: Run tasks on Non Controller Kafka Brokers serially
  include: "{{ ordered_action_tasks }}"
  delegate_to: "{{ item }}"
  loop: "{{ groups['kafka_broker'] }}"
  when:
    - "hostvars[item].inventory_hostname == inventory_hostname"
    - hostvars[item].broker_id|int != controller_json.brokerid|int

- name: Run tasks on Kafka Broker Controller
  include: "{{ ordered_action_tasks }}"
  when: broker_id|int == controller_json.brokerid|int
