confluent_controlcenter_internal_topics_replication: 3
confluent_metrics_topic_replication: 3
confluent_monitoring_interceptor_topic_replication: 3
confluent_controlcenter_command_topic_replication: 3

confluent:
  control:
    center:
      user: cp-control-center
      group: confluent
      config_file: /etc/confluent-control-center/control-center-production.properties
      service_name: confluent-control-center
      systemd_override: /etc/systemd/system/confluent-control-center.service.d
      environment:
        CONTROL_CENTER_HEAP_OPTS: "-Xmx6g"
      config:
        confluent.controlcenter.streams.num.stream.threads: 8
        confluent.controlcenter.data.dir: /var/lib/confluent/control-center
        confluent.controlcenter.ksql.enable: 'true'
        confluent.controlcenter.schema.registry.enable: 'true'
        confluent.controlcenter.streams.ssl.endpoint.identification.algorithm: ""
        confluent.controlcenter.rest.ssl.endpoint.identification.algorithm: ""
        confluent.controlcenter.command.topic.replication: "{{confluent_controlcenter_command_topic_replication}}"
        confluent.controlcenter.internal.topics.replication: "{{confluent_controlcenter_internal_topics_replication}}"
        confluent.metrics.topic.replication: "{{confluent_metrics_topic_replication}}"
        confluent.monitoring.interceptor.topic.replication: "{{confluent_monitoring_interceptor_topic_replication}}"
      systemd:
        enabled: yes
        state: started
