control_center_config_defaults:
  confluent.controlcenter.rest.listeners: http://0.0.0.0:9021
  confluent.controlcenter.streams.num.stream.threads: 8
  confluent.controlcenter.data.dir: /var/lib/confluent/control-center
  confluent.controlcenter.ksql.enable: true
  confluent.controlcenter.schema.registry.enable: true
  confluent.controlcenter.streams.ssl.endpoint.identification.algorithm: ""
  confluent.controlcenter.rest.ssl.endpoint.identification.algorithm: ""
  confluent.controlcenter.ksql.url: "{{ client.ksql.endpoint }}"
  confluent.controlcenter.schema.registry.url: "{{ client.schema.registry.urls }}"
  confluent.controlcenter.connect.cluster: "{{ client.connect.urls }}"
  bootstrap.servers: "{{ client.broker.bootstrap_servers }}"
  zookeeper.connect: "{{ client.zookeeper.connect }}"
confluent:
  control:
    center:
      user: cp-control-center
      group: confluent
      config_file: /etc/confluent-control-center/control-center-production.properties
      service_name: confluent-control-center
      systemd_override: /etc/systemd/system/confluent-control-center.service.d
      environment:
        CONTROL_CENTER_HEAP_OPTS: "-Xmx6g"
      config: "{{ client_config | append_prefix(['confluent.controlcenter.streams.', 'confluent.controlcenter.rest.']) | combine(control_center_config_defaults)}}"
      systemd:
        enabled: yes
        state: started
