- name: Install apt prerequisites
  apt:
    name: apt-transport-https
- name: Install Java
  apt:
    name: "openjdk-8-jdk"
    update_cache: yes
- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'
