- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
- import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- import_tasks: debian.yml
  when: ansible_distribution == 'Debian'
- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'
