---
- name: ksql create group
  group:
    name: "{{ ksql.group }}"
  become: yes

- name: ksql create user
  user:
    name: "{{ ksql.user }}"
    comment: "Connect Distributed User"
    system: yes
    group: "{{ ksql.group }}"
  become: yes

- name: ksql create config
  template:
    src: ksql/ksql.properties.j2
    dest: "{{ ksql.config_file }}"
    mode: 0640
    owner: "{{ ksql.user }}"
    group: "{{ ksql.group }}"
  notify:
    - restart ksql
  become: yes
- name: ksql configure service
  systemd:
    name: "{{ ksql.service_name }}"
    enabled: "{{ ksql.systemd.enabled }}"
    state: "{{ ksql.systemd.state }}"
  become: yes
