- hosts: preflight
  tasks:
  - import_role:
      name: confluent.preflight
- hosts: ssl_CA
  tasks:
  - name: Include TLS vars
    include_vars: kerberos_ssl_customcerts/vars/security_vars.yml
  - import_role:
      name: confluent.ssl_customcerts
- hosts: kerberos
  tasks:
  - import_role:
      name: confluent.kerberos
- hosts: zookeeper
  tasks:
  - import_role:
      name: confluent.zookeeper
- hosts: broker
  tasks:
  - name: Include TLS vars
    include_vars: kerberos_ssl_customcerts/vars/security_vars.yml
  - import_role:
      name: confluent.kafka-broker
- hosts: schema-registry
  tasks:
  - name: Include TLS vars
    include_vars: kerberos_ssl_customcerts/vars/security_vars.yml
  - import_role:
      name: confluent.schema-registry
- hosts: connect-distributed
  tasks:
  - name: Include TLS vars
    include_vars: kerberos_ssl_customcerts/vars/security_vars.yml
  - import_role:
      name: confluent.connect-distributed
- hosts: ksql
  tasks:
  - name: Include TLS vars
    include_vars: kerberos_ssl_customcerts/vars/security_vars.yml
  - import_role:
      name: confluent.ksql
- hosts: control-center
  tasks:
  - name: Include TLS vars
    include_vars: kerberos_ssl_customcerts/vars/security_vars.yml
  - import_role:
      name: confluent.control-center
- hosts: kafka-rest
  tasks:
  - name: Include TLS vars
    include_vars: kerberos_ssl_customcerts/vars/security_vars.yml
  - import_role:
      name: confluent.kafka-rest
- hosts: tools
  tasks:
  - name: Include TLS vars
    include_vars: kerberos_ssl_customcerts/vars/security_vars.yml
  - import_role:
      name: confluent.tools
    tags:
      - post-install

