all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ec2-user
    ansible_become: true
    realm: confluent.example.com
    kdc_hostname: <hostname of machine with KDC installed ex. ip-172-31-45-82.us-east-2.compute.internal>
    admin_hostname: <hostname of machine with KDC installed ex. ip-172-31-45-82.us-east-2.compute.internal>
    keytab_source_dir: <path to your keytabs, ex. /root/keytabs/, note the / at the end is mandatory>
    security_mode: kerberos_ssl_customcerts
preflight:
  hosts:
    ip-172-31-34-246.us-east-2.compute.internal:
    ip-172-31-37-15.us-east-2.compute.internal:
    ip-172-31-34-231.us-east-2.compute.internal:
    ip-172-31-45-24.us-east-2.compute.internal:
ssl_CA:
  hosts:
    ip-172-31-45-24.us-east-2.compute.internal:
zookeeper:
  hosts:
    ip-172-31-34-246.us-east-2.compute.internal:
    ip-172-31-37-15.us-east-2.compute.internal:
    ip-172-31-34-231.us-east-2.compute.internal:
broker:
  hosts:
    ip-172-31-34-246.us-east-2.compute.internal:
      kafka:
        broker:
          id: 1
    ip-172-31-37-15.us-east-2.compute.internal:
      kafka:
        broker:
          id: 2
    ip-172-31-34-231.us-east-2.compute.internal:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    ip-172-31-34-246.us-east-2.compute.internal:
control-center:
  hosts:
    ip-172-31-37-15.us-east-2.compute.internal:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: ip-172-31-34-246.us-east-2.compute.internal:8083
connect-distributed:
  hosts:
    ip-172-31-34-246.us-east-2.compute.internal:
kafka-rest:
  hosts:
    ip-172-31-34-246.us-east-2.compute.internal:
ksql:
  hosts:
    ip-172-31-37-15.us-east-2.compute.internal:
kerberos:
  hosts:
    ip-172-31-34-246.us-east-2.compute.internal:
    ip-172-31-37-15.us-east-2.compute.internal:
    ip-172-31-34-231.us-east-2.compute.internal:
