- name: Create Kafka properties file
  file:
    path: "{{kafka_config_dir}}"
    state: directory

- name: Kafka base settings block
  blockinfile:
    path: "{{kafka_config_dir}}/server.properties"
    create: yes
    marker: "<!-- Base Confluent Kafka settings -->"
    content: |
        broker.id={{kafka_broker_id}}
        metric.reporters=io.confluent.metrics.reporter.ConfluentMetricsReporter
        confluent.metrics.reporter.bootstrap.servers=localhost:9092
        delete.topic.enable=true
        listeners=PLAINTEXT://:9092
        log.dirs={{kafka_log_dirs}}
        zookeeper.connect={{kafka_zookeeper_connect}}
