---
- name: Generate CA for Self Signed Certs
  hosts: zookeeper[0]
  tasks:
  - import_role:
      name: confluent.variables_handlers
  - name: Create Certificate Authority and Copy to Ansible Host
    include_tasks: ../../../../tasks/certificate_authority.yml
    when:
      - self_signed|bool
      - regenerate_ca|bool
      - ssl_enabled|bool

- name: Host Prerequisites
  hosts: zookeeper:kafka_broker:schema_registry:kafka_connect:ksql:kafka_rest
  tasks:
  - import_role:
      name: confluent.common

- name: Zookeeper Provisioning
  hosts: zookeeper
  tasks:
    - include_role:
        name: confluent.zookeeper

- name: Kafka Broker Provisioning
  hosts: kafka_broker
  tasks:
    - include_role:
        name: confluent.kafka_broker

- name: Schema Registry Provisioning
  hosts: schema_registry
  tasks:
    - include_role:
        name: confluent.schema_registry

- name: Kafka Connect Provisioning
  hosts: kafka_connect
  tasks:
    - include_role:
        name: confluent.kafka_connect

- name: KSQL Provisioning
  hosts: ksql
  tasks:
    - include_role:
        name: confluent.ksql

- name: Kafka Rest Provisioning
  hosts: kafka_rest
  tasks:
  - import_role:
      name: confluent.kafka_rest

- name: Control Center Provisioning
  hosts: control_center
  tasks:
    - include_role:
        name: confluent.control_center
