---
- name: Verify - zookeeper
  hosts: zookeeper
  gather_facts: no
  tasks:
    - name: Get Stats on Keytab file
      stat:
        path: /etc/security/keytabs/zookeeper-zookeeper1.keytab
      register: keytab

    - name: Assert ownership on keytab file
      assert:
        that:
          - keytab.stat.gr_name == "confluent"
          - keytab.stat.pw_name == "cp-kafka"
        quiet: yes

    - name: Check jaas config
      shell: grep -Fq 'zookeeper/{{inventory_hostname}}.confluent@REALM.EXAMPLE.COM' /etc/kafka/zookeeper_jaas.conf
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: no
  tasks:
    - name: Get Stats on Keytab file
      stat:
        path: "/etc/security/keytabs/kafka_broker-{{inventory_hostname}}.keytab"
      register: keytab

    - name: Assert ownership on keytab file
      assert:
        that:
          - keytab.stat.gr_name == "confluent"
          - keytab.stat.pw_name == "cp-kafka"
        quiet: yes

    - name: Check jaas config
      shell: |
        grep -Fq 'kafka/{{inventory_hostname}}.confluent@REALM.EXAMPLE.COM' /etc/kafka/kafka_server_jaas.conf
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - schema_registry
  hosts: schema_registry
  gather_facts: no
  tasks:
    - name: Get Stats on Keytab file
      stat:
        path: "/etc/security/keytabs/schema_registry-{{inventory_hostname}}.keytab"
      register: keytab

    - name: Assert ownership on keytab file
      assert:
        that:
          - keytab.stat.gr_name == "confluent"
          - keytab.stat.pw_name == "cp-schema-registry"
        quiet: yes

- name: Verify - kafka_rest
  hosts: kafka_rest
  gather_facts: no
  tasks:
    - name: Get Stats on Keytab file
      stat:
        path: "/etc/security/keytabs/kafka_rest-{{inventory_hostname}}.keytab"
      register: keytab

    - name: Assert ownership on keytab file
      assert:
        that:
          - keytab.stat.gr_name == "confluent"
          - keytab.stat.pw_name == "cp-kafka-rest"
        quiet: yes

- name: Verify - kafka_connect
  hosts: kafka_connect
  gather_facts: no
  tasks:
    - name: Get Stats on Keytab file
      stat:
        path: "/etc/security/keytabs/kafka_connect-{{inventory_hostname}}.keytab"
      register: keytab

    - name: Assert ownership on keytab file
      assert:
        that:
          - keytab.stat.gr_name == "confluent"
          - keytab.stat.pw_name == "cp-kafka-connect"
        quiet: yes

- name: Verify - ksql
  hosts: ksql
  gather_facts: no
  tasks:
    - name: Get Stats on Keytab file
      stat:
        path: "/etc/security/keytabs/ksql-{{inventory_hostname}}.keytab"
      register: keytab

    - name: Assert ownership on keytab file
      assert:
        that:
          - keytab.stat.gr_name == "confluent"
          - keytab.stat.pw_name == "cp-ksql"
        quiet: yes

    - name: Check jaas config
      shell: |
        grep -Fq 'ksql/{{inventory_hostname}}.confluent@REALM.EXAMPLE.COM' /etc/ksql/ksql-server_jaas.conf
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - control_center
  hosts: control_center
  gather_facts: no
  tasks:
    - name: Get Stats on Keytab file
      stat:
        path: "/etc/security/keytabs/control_center-{{inventory_hostname}}.keytab"
      register: keytab

    - name: Assert ownership on keytab file
      assert:
        that:
          - keytab.stat.gr_name == "confluent"
          - keytab.stat.pw_name == "cp-control-center"
        quiet: yes
