kafka_rest_config_default:
  listeners: http://0.0.0.0:8082
  client.ssl.endpoint.identification.algorithm: ""
  bootstrap.servers: "{{ client.broker.bootstrap_servers }}"
  schema.registry.url: "{{ client.schema.registry.urls }}"
kafkarest:
  user: cp-kafka-rest
  group: confluent
  config_file: /etc/kafka-rest/kafka-rest.properties
  service_name: confluent-kafka-rest
  systemd_override: /etc/systemd/system/confluent-kafka-rest.service.d
  config: "{{ client_config | append_prefix(['consumer.', 'producer.']) | combine(kafka_rest_config_default) }}"
  environment:
    LOG_DIR: /var/log/kafka-rest
  systemd:
    enabled: yes
    state: started
