---
kafka:
  ports:
    plain: 9092
    sasl_ssl: 9093
    sasl_plaintext: 9094
    ssl: 9095
  ssl_truststore_location: /tmp/kafka.client.truststore.jks
  ssl_keystore_location: /tmp/kafka.server.keystore.jks
  store_password: password123

kafka_port: "{{kafka.ports.plain}}"
connect_port: 8083
