---

- name: Grab Master Token
  uri:
    url: "{{ keycloak_master_token_url }}"
    method: POST
    validate_certs: false
    headers:
      Content-Type: application/x-www-form-urlencoded
    body:
      client_id: "{{ keycloak_master_client }}"
      username: "{{ keycloak_master_username }}"
      password: "{{ keycloak_master_password }}"
      grant_type: "password"
    body_format: form-urlencoded
  register: keycloak_master_token

- name: extract master_token
  set_fact:
    keycloak_master_access_token: "{{ keycloak_master_token.json.access_token }}"

- name: debug processed master token
  debug:
    msg: "{{ keycloak_master_access_token }}"

- name: Create New Realm on Keycloak Server
  community.general.keycloak_realm:
    state: present
    realm: "{{ keycloak_realm_name }}"
    id: "{{ keycloak_realm_name }}"
    enabled: true
    auth_keycloak_url: "{{ keycloak_oauth_server_base_url }}"
    auth_client_id: "{{ keycloak_master_client }}"
    auth_username: "{{ keycloak_master_username }}"
    auth_password: "{{ keycloak_master_password }}"
    auth_realm: master
    validate_certs: false
  register: keycloak_realm

- name: debug keycloak_realm
  debug:
    msg: "{{ keycloak_realm }}"


# - name: Create New Keycloak Client using uri
#   uri:
#     url: "{{ keycloak_oauth_server_base_url }}/admin/realms/{{ keycloak_realm_name }}/clients"
#     method: POST 
#     validate_certs: false
#     headers:
#       Content-Type: application/json
#       Authorization: "Bearer {{ keycloak_master_access_token }}"
#     body_format: json
#     status_code: 200,201,409
#     body: 
#       clientId: "{{ item }}"
#       enabled: true
#       protocol: openid-connect
#       attributes: {}
#       consentRequired: false
#       publicClient: false
#       serviceAccountsEnabled: true
#       authorizationServicesEnabled: true
#       clientAuthenticatorType: client-secret
#   register: keycloak_client
#   loop:
#     - "client1"
#     - "client2"

- name: Create New Keycloak Client
  community.general.keycloak_client:
    state: present
    realm: "{{ keycloak_realm_name }}"
    client_id: "{{ item }}"
    enabled: true
    protocol: openid-connect
    service_accounts_enabled: true
    authorization_services_enabled: true
    client_authenticator_type: client-secret
    auth_keycloak_url: "{{ keycloak_oauth_server_base_url }}"
    auth_client_id: "{{ keycloak_master_client }}"
    auth_username: "{{ keycloak_master_username }}"
    auth_password: "{{ keycloak_master_password }}"
    auth_realm: master
    validate_certs: false
    public_client: false
  register: keycloak_client
  loop: "{{ keycloak_clients }}"

- name: save keycloak_ids
  set_fact:
    cli_ids: "{{ cli_ids|default([]) + [item.end_state.id] }}"
  loop: "{{ keycloak_client.results }}"

- name: debug cli_ids
  debug:
    msg: "hi->{{ cli_ids }}"

- name: Get Client Secret
  community.general.keycloak_clientsecret_info:
    id: "{{ item }}"
    # client_id: "{{ item}}"
    realm: "{{ keycloak_realm_name }}"
    auth_client_id: "{{ keycloak_master_client }}"
    auth_keycloak_url: "{{ keycloak_oauth_server_base_url }}"
    # token: "{{ keycloak_master_access_token }}"
    validate_certs: false
    auth_username: "{{ keycloak_master_username }}"
    auth_password: "{{ keycloak_master_password }}"
    auth_realm: master
  register: keycloak_client_secret
  loop: "{{ cli_ids }}"

- name: debug keycloak_client_secret
  debug:
    msg: "{{ item.clientsecret_info.value }}"
  loop: "{{ keycloak_client_secret.results }}"
  loop_control:
    label: "{{ item.clientsecret_info.value }}"


- name: save client_secrets
  set_fact:
    cli_secrets: "{{ cli_secrets|default([]) + [item.clientsecret_info.value] }}"
  loop: "{{ keycloak_client_secret.results }}"
  loop_control:
    label: "{{ item.clientsecret_info.value }}"

- name: debug cli_secrets
  debug:
    msg: "hi->{{ cli_secrets }}"

- name: Merge cli name, cli id, cli secrets
  set_fact:
    clients_info_list: "{{ clients_info_list|default([]) + [{'client_name':item.0,'client_id':item.1,'client_secret':item.2}] }}"
  with_together:
    - "{{ keycloak_clients }}"
    - "{{ cli_ids }}"
    - "{{ cli_secrets }}"
  
- name: debug clients_info_list
  debug:
    msg: "{{ clients_info_list }}"
  
- name: Merge cli name, cli id, cli secrets
  set_fact:
    clients_info_dict: "{{ clients_info_dict|default({}) | combine( {item.0: {'id':item.1}| combine({'secret':item.2}) }) }}"
  with_together:
    - "{{ keycloak_clients }}"
    - "{{ cli_ids }}"
    - "{{ cli_secrets }}"

- name: debug clients_info_dict
  debug:
    msg: "{{ clients_info_dict }}"
