---
- set_fact:
    idp_body: [["client_id","{{ master_client }}"],["username","{{ master_username }}"],["password","{{ master_password }}"],["grant_type","password"]]

- name: Grab Master Token
  uri:
    url: "{{ master_token_url }}"
    method: POST
    validate_certs: false
    return_content: true
    status_code: 200
    body: "{{ idp_body }}"
  register: master_token
  until: master_token.status == 200
  retries: 10
  delay: 5

- name: debug unprocessed master token
  debug:
    msg: "{{ master_token }}"

- name: extract master_token
  set_fact:
    master_access_token: "{{ (master_token.content | from json).access_token }}"

- name: debug unprocessed master token
  debug:
    msg: "{{ master_access_token }}"
