---
# tasks file for confluent.test.oauth
- name: Setup Realm
  include_tasks: create_realm.yml

- name: Set MDS secret
  set_fact:
    oauth_client_password: "{{ clients_info_dict['mds']['secret'] }}"
    oauth_client_id: "{{ clients_info_dict['mds']['id'] }}"
  delegate_to: kafka-broker1

- name: debug oauth_client_password
  debug:
    msg: "username:password -> {{oauth_client_id}}:{{ oauth_client_password }}"

- name: Set SR secret
  set_fact:
    schema_registry_oauth_password: "{{ clients_info_dict['schema-registry']['secret'] }}"
    schema_registry_oauth_user: "{{ clients_info_dict['schema-registry']['id'] }}"
  delegate_to: schema-registry1