---
# tasks file for confluent.test.oauth
- name: Setup Realm
  include_tasks: create_realm.yml

- name: Create OAuth Credentials Directory
  file:
    path: "{{lookup('env', 'MOLECULE_SCENARIO_DIRECTORY')}}/oauth_pass"
    state: directory
    mode: '755'
  delegate_to: localhost

- name: Create OAuth Secrets File
  copy:
    content: "{{ clients_info_dict[item]['secret'] }}"
    dest: "{{lookup('env', 'MOLECULE_SCENARIO_DIRECTORY')}}/oauth_pass/{{item}}_secret.yml"
    mode: '777'
  ignore_errors: true
  delegate_to: localhost
  loop: "{{ keycloak_clients }}"
