- name: broker group
  group:
    name: "{{kafka.broker.group}}"
- name: broker user
  user:
    name: "{{kafka.broker.user}}"
    comment: "Kafka User"
    system: yes
    group: "{{kafka.broker.group}}"
- name: broker config
  template:
    src: server.properties.j2
    dest: "{{kafka.broker.config_file}}"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
  notify:
    - restart kafka
- name: broker configure service
  systemd:
    name: "{{kafka.broker.service_name}}"
    enabled: "{{kafka.broker.systemd.enabled}}"
    state: "{{kafka.broker.systemd.state}}"
