---
### Installs Zookeeper, Kafka Broker, Schema Registry on centos8
### Digest authentication enabled.
### SASL SCRAM enabled.
### Customer Zookeeper Root.

driver:
  name: docker
platforms:
  - name: zookeeper1
    hostname: zookeeper1.confluent
    groups:
      - zookeeper
    image: redhat/ubi9-minimal
    dockerfile: ../Dockerfile-rhel9-java17.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: zookeeper2
    hostname: zookeeper2.confluent
    groups:
      - zookeeper
    image: redhat/ubi9-minimal
    dockerfile: ../Dockerfile-rhel9-java17.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: zookeeper3
    hostname: zookeeper3.confluent
    groups:
      - zookeeper
    image: redhat/ubi9-minimal
    dockerfile: ../Dockerfile-rhel9-java17.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-broker1
    hostname: kafka-broker1.confluent
    groups:
      - kafka_broker
    image: redhat/ubi9-minimal
    dockerfile: ../Dockerfile-rhel9-java17.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-broker2
    hostname: kafka-broker2.confluent
    groups:
      - kafka_broker
    image: redhat/ubi9-minimal
    dockerfile: ../Dockerfile-rhel9-java17.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-broker3
    hostname: kafka-broker3.confluent
    groups:
      - kafka_broker
    image: redhat/ubi9-minimal
    dockerfile: ../Dockerfile-rhel9-java17.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: schema-registry1
    hostname: schema-registry1.confluent
    groups:
      - schema_registry
    image: redhat/ubi9-minimal
    dockerfile: ../Dockerfile-rhel9-java17.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
provisioner:
  inventory:
    group_vars:
      all:
        scenario_name: zookeeper-digest-rhel
        confluent_common_repository_redhat_clients_baseurl: https://packages.confluent.io/clients/rpm/centos/8/x86_64
        confluent_common_repository_redhat_clients_gpgcheck: 0
        confluent_common_repository_redhat_main_gpgcheck: 0
        zookeeper_sasl_protocol: digest
        sasl_protocol: scram

        zookeeper_chroot: "/kafka"
