---
driver:
  name: docker
platforms:
  # Unset env vars resolve to the empty string
  - name: zookeeper1${JOB_BASE_NAME}${BUILD_NUMBER}
    hostname: zookeeper1${JOB_BASE_NAME}${BUILD_NUMBER}.confluent${JOB_BASE_NAME}${BUILD_NUMBER}
    groups:
      - zookeeper
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${JOB_BASE_NAME}${BUILD_NUMBER}
  - name: kafka-broker1${JOB_BASE_NAME}${BUILD_NUMBER}
    hostname: kafka-broker1${JOB_BASE_NAME}${BUILD_NUMBER}.confluent${JOB_BASE_NAME}${BUILD_NUMBER}
    groups:
      - kafka_broker
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${JOB_BASE_NAME}${BUILD_NUMBER}
  - name: schema-registry1${JOB_BASE_NAME}${BUILD_NUMBER}
    hostname: schema-registry1${JOB_BASE_NAME}${BUILD_NUMBER}.confluent${JOB_BASE_NAME}${BUILD_NUMBER}
    groups:
      - schema_registry
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${JOB_BASE_NAME}${BUILD_NUMBER}
  - name: kafka-rest1${JOB_BASE_NAME}${BUILD_NUMBER}
    hostname: kafka-rest1${JOB_BASE_NAME}${BUILD_NUMBER}.confluent${JOB_BASE_NAME}${BUILD_NUMBER}
    groups:
      - kafka_rest
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${JOB_BASE_NAME}${BUILD_NUMBER}
  - name: kafka-connect1${JOB_BASE_NAME}${BUILD_NUMBER}
    hostname: kafka-connect1${JOB_BASE_NAME}${BUILD_NUMBER}.confluent${JOB_BASE_NAME}${BUILD_NUMBER}
    groups:
      - kafka_connect
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${JOB_BASE_NAME}${BUILD_NUMBER}
  - name: ksql1${JOB_BASE_NAME}${BUILD_NUMBER}
    hostname: ksql1${JOB_BASE_NAME}${BUILD_NUMBER}.confluent${JOB_BASE_NAME}${BUILD_NUMBER}
    groups:
      - ksql
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${JOB_BASE_NAME}${BUILD_NUMBER}
  - name: control-center1${JOB_BASE_NAME}${BUILD_NUMBER}
    hostname: control-center1${JOB_BASE_NAME}${BUILD_NUMBER}.confluent${JOB_BASE_NAME}${BUILD_NUMBER}
    groups:
      - control_center
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    ## Commenting below to avoid port collision on jenkins server
    ## Uncomment to view c3 in browser at localhost:9021
    published_ports:
      - "9021:9021"
    networks:
      - name: confluent${JOB_BASE_NAME}${BUILD_NUMBER}
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  playbooks:
    converge: ../../../../all.yml
  inventory:
    group_vars:
      all:
        scenario_name: plaintext-basic-rhel

        # Kafka Rest API Basic Auth
        kafka_broker_copy_files:
          - source_path: "roles/confluent.test/molecule/{{scenario_name}}/password.properties"
            destination_path: /etc/kafka-rest/password.properties
          - source_path: "roles/confluent.test/molecule/{{scenario_name}}/rest-jaas.properties"
            destination_path: /etc/kafka-rest/rest-jaas.properties

        kafka_broker_custom_properties:
          kafka.rest.resource.extension.class: io.confluent.kafkarest.security.KafkaRestSecurityResourceExtension
          kafka.rest.confluent.rest.auth.propogate.method: JETTY_AUTH
          kafka.rest.authentication.method: BASIC
          kafka.rest.authentication.realm: KafkaRest
          kafka.rest.authentication.roles: thisismyrole
          confluent.balancer.enable: 'true'

        kafka_broker_custom_java_args: "-Djava.security.auth.login.config=/etc/kafka-rest/rest-jaas.properties"

        kafka_broker_rest_health_check_user: thisismyusername
        kafka_broker_rest_health_check_password: thisismypass

        # Schema Registry Basic Auth
        schema_registry_copy_files:
          - source_path: "roles/confluent.test/molecule/{{scenario_name}}/password.properties"
            destination_path: /etc/kafka-rest/password.properties
          - source_path: "roles/confluent.test/molecule/{{scenario_name}}/rest-jaas.properties"
            destination_path: /etc/kafka-rest/rest-jaas.properties

        schema_registry_custom_properties:
          authentication.method: BASIC
          authentication.realm: KafkaRest
          authentication.roles: thisismyrole

        schema_registry_custom_java_args: "-Djava.security.auth.login.config=/etc/kafka-rest/rest-jaas.properties"

        schema_registry_health_check_user: thisismyusername
        schema_registry_health_check_password: thisismypass

        # Connect Basic Auth Not working
        kafka_connect_copy_files:
          - source_path: "roles/confluent.test/molecule/{{scenario_name}}/connect.password"
            destination_path: /etc/kafka-connect/connect.password
          - source_path: "roles/confluent.test/molecule/{{scenario_name}}/connect-jaas.properties"
            destination_path: /etc/kafka-connect/connect-jaas.properties

        kafka_connect_custom_properties:
          rest.extension.classes: org.apache.kafka.connect.rest.basic.auth.extension.BasicAuthSecurityRestExtension

        kafka_connect_custom_java_args: "-Djava.security.auth.login.config=/etc/kafka-connect/connect-jaas.properties"

        kafka_connect_health_check_user: thisismyusername
        kafka_connect_health_check_password: thisismypass

        # ksqlDB Basic Auth
        ksql_copy_files:
          - source_path: "roles/confluent.test/molecule/{{scenario_name}}/password.properties"
            destination_path: /etc/kafka-rest/password.properties
          - source_path: "roles/confluent.test/molecule/{{scenario_name}}/rest-jaas.properties"
            destination_path: /etc/kafka-rest/rest-jaas.properties

        ksql_custom_properties:
          authentication.method: BASIC
          authentication.realm: KafkaRest
          authentication.roles: thisismyrole

        ksql_custom_java_args: "-Djava.security.auth.login.config=/etc/kafka-rest/rest-jaas.properties"

        ksql_health_check_user: thisismyusername
        ksql_health_check_password: thisismypass

        # Rest Proxy Basic Auth
        kafka_rest_copy_files:
          - source_path: "roles/confluent.test/molecule/{{scenario_name}}/password.properties"
            destination_path: /etc/kafka-rest/password.properties
          - source_path: "roles/confluent.test/molecule/{{scenario_name}}/rest-jaas.properties"
            destination_path: /etc/kafka-rest/rest-jaas.properties

        kafka_rest_custom_properties:
          rest.extension.classes: org.apache.kafka.connect.rest.basic.auth.extension.BasicAuthSecurityRestExtension
          # kafka.rest.resource.extension.class: io.confluent.kafkarest.security.KafkaRestSecurityResourceExtension
          # kafka.rest.confluent.rest.auth.propogate.method: JETTY_AUTH
          authentication.method: BASIC
          authentication.realm: KafkaRest
          authentication.roles: thisismyrole

        kafka_rest_custom_java_args: "-Djava.security.auth.login.config=/etc/kafka-rest/rest-jaas.properties"

        kafka_rest_health_check_user: thisismyusername
        kafka_rest_health_check_password: thisismypass

        # C3 Basic Auth
        control_center_copy_files:
          - source_path: "roles/confluent.test/molecule/{{scenario_name}}/password.properties"
            destination_path: /etc/kafka-rest/password.properties
          - source_path: "roles/confluent.test/molecule/{{scenario_name}}/rest-jaas.properties"
            destination_path: /etc/kafka-rest/rest-jaas.properties

        control_center_custom_properties:
          confluent.controlcenter.rest.authentication.method: BASIC
          confluent.controlcenter.rest.authentication.realm: KafkaRest
          confluent.controlcenter.rest.authentication.roles: thisismyrole,Restricted
          confluent.controlcenter.auth.restricted.roles: Restricted
          confluent.controlcenter.auth.session.expiration.ms: 600000

        control_center_custom_java_args: "-Djava.security.auth.login.config=/etc/kafka-rest/rest-jaas.properties"

        control_center_health_check_user: thisismyusername
        control_center_health_check_password: thisismypass

verifier:
  name: ansible
lint: |
  set -e
  yamllint -c ../../.yamllint ../..
scenario:
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
