---
- name: Verify
  hosts: kafka_broker,kafka_rest,schema_registry,ksql,control_center
  gather_facts: false
  tasks:
    - name: Get stats on copied file
      stat:
        path: /etc/kafka-rest/rest-jaas.properties
      register: jaas_file

    - name: Assert copied file's permissions correct
      assert:
        that:
          - jaas_file.stat.exists
          - jaas_file.stat.gr_name == 'confluent'
        quiet: true
