---
driver:
  name: docker
platforms:
  - name: centos7
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: ubuntu1604
    image: geerlingguy/docker-ubuntu1604-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  # - name: debian9
  #   image: geerlingguy/docker-debian9-ansible
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        hello: world
verifier:
  name: ansible
