---
- name: Verify
  hosts: all
  tasks:

  - name: Get Package Facts
    package_facts:
      manager: auto

  - name: Example assertion
    assert:
      that: "ansible_facts.packages['java-1.8.0-openjdk'] is defined"
    when: ansible_os_family == 'RedHat'

  - name: Example assertion
    assert:
      that: "ansible_facts.packages['openjdk-8-jdk'] is defined"
    when: ansible_os_family == "Debian"
