---
- name: Verify
  hosts: all
  tasks:
    - name: Get Package Facts
      package_facts:
        manager: auto

    - name: Assert java installed - Redhat
      assert:
        that: "ansible_facts.packages['java-1.8.0-openjdk'] is defined"
      when: ansible_os_family == 'RedHat'

    - name: Assert java installed - Debian
      assert:
        that: "ansible_facts.packages['openjdk-8-jdk'] is defined"
      when: ansible_os_family == "Debian"

    - name: Check if jolokia jar exists
      stat:
        path: /opt/jolokia/jolokia.jar
      register: jolokia_jar

    - name: Assert jolokia jar downloaded
      assert:
        that: jolokia_jar.stat.exists

    - name: Check if prometheus jar exists
      stat:
        path: /opt/prometheus/jmx_prometheus_javaagent.jar
      register: prometheus_jar

    - name: Assert prometheus jar not downloaded
      assert:
        that: not prometheus_jar.stat.exists

    - name: Check if custom repofile exists
      stat:
        path: /etc/yum.repos.d/custom-confluent.repo
      register: custom_repofile

    - name: Assert custom repofile created
      assert:
        that: not custom_repofile.stat.exists
