---
- name: Verify
  hosts: default
  tasks:
    - name: Get Package Facts
      package_facts:
        manager: auto

    - name: Assert java installed - Redhat
      assert:
        that: "ansible_facts.packages['java-1.8.0-openjdk'] is defined"
        quiet: yes
      when: ansible_os_family == 'RedHat'

    - name: Assert java installed - Debian
      assert:
        that: "ansible_facts.packages['openjdk-8-jdk'] is defined"
        quiet: yes
      when: ansible_os_family == "Debian"

    - name: Get stats on jolokia jar
      stat:
        path: /opt/jolokia/jolokia.jar
      register: jolokia_jar

    - name: Get stats on prometheus jar
      stat:
        path: /opt/prometheus/jmx_prometheus_javaagent.jar
      register: prometheus_jar

    - name: Get stats on custom repofile
      stat:
        path: /etc/yum.repos.d/custom-confluent.repo
      register: custom_repofile

    - name: Assert files exist properly
      assert:
        that:
          - jolokia_jar.stat.exists
          - not prometheus_jar.stat.exists
          - not custom_repofile.stat.exists
        quiet: yes

- name: Verify
  hosts: custom
  tasks:
    - name: Get stats on jolokia jar
      stat:
        path: /opt/jolokia/jolokia.jar
      register: jolokia_jar

    - name: Get stats on prometheus jar
      stat:
        path: /opt/prometheus/jmx_prometheus_javaagent.jar
      register: prometheus_jar

    - name: Get stats on custom repofile
      stat:
        path: /etc/yum.repos.d/custom-confluent.repo
      register: custom_repofile

    - name: Assert files exist properly
      assert:
        that:
          - not jolokia_jar.stat.exists
          - prometheus_jar.stat.exists
          - custom_repofile.stat.exists
        quiet: yes
