schema_registry_listener_port: 8081
schema_registry_config_defaults:
  kafkastore.bootstrap.servers: "{{ groups['broker'] | format_host('{security_mode}://{host}:{port}', {'port': broker.config.port, 'security_mode': security_mode.upper() }) | join(',') }}"
  listeners: http://0.0.0.0:{{schema_registry_listener_port}}
  kafkastore.topic: _schemas
  debug: false
  kafkastore.ssl.endpoint.identification.algorithm: ""
schema:
  registry:
    user: cp-schema-registry
    group: confluent
    config_file: /etc/schema-registry/schema-registry.properties
    service_name: confluent-schema-registry
    systemd_override: /etc/systemd/system/confluent-schema-registry.service.d
    config: "{{ client_config | append_prefix('kafkastore.') | combine(schema_registry_config_defaults) }}"
    environment:
      SCHEMA_REGISTRY_HEAP_OPTS: "-Xmx1000M"
    systemd:
      enabled: yes
      state: started
