---
- name: Register Kafka Connect Subgroups
  set_fact: subgroups="{{ ((subgroups | default([])) + hostvars[item].group_names) | difference('kafka_broker, ksql, kafka_connect, kafka_rest, kerberos, ksql, schema_registry, zookeeper, kafka_broker_parallel, ksql_parallel, kafka_connect_parallel, kafka_rest_parallel, kerberos_parallel, ksql_parallel, schema_registry_parallel, zookeeper_parallel') }}"
  with_items: "{{groups['kafka_connect']}}"

- name: Add Role Bindings for Connect
  include_tasks: role_bindings_connector.yml
  when:
    - rbac_enabled|bool
    - not ansible_check_mode

- name: Register connector configs and remove deleted connectors for single cluster
  confluent.platform.kafka_connectors:
    connect_url: "{{kafka_connect_http_protocol}}://{{ hostvars[inventory_hostname]|confluent.platform.resolve_hostname }}:{{kafka_connect_rest_port}}/connectors"
    active_connectors: "{{ kafka_connect_connectors }}"
    timeout: "{{ kafka_connect_deploy_connector_timeout }}"
    username: "{% if rbac_enabled %}{{kafka_connect_ldap_user}}{% else %}{{none}}{% endif %}"
    password: "{% if rbac_enabled %}{{kafka_connect_ldap_password}}{% else %}{{none}}{% endif %}"
    client_cert: "{% if (ssl_provided_keystore_and_truststore and ssl_mutual_auth_enabled) %}{{kafka_connect_cert_path}}{% elif ssl_mutual_auth_enabled %}{{certs_chain}}{% else %}{{none}}{% endif %}"
    client_key: "{% if ssl_mutual_auth_enabled %}{{kafka_connect_key_path}}{% else %}{{none}}{% endif %}"
  when:
    - kafka_connect_connectors is defined
    - subgroups|length == 0
  run_once: true

- name: Register connector configs and remove deleted connectors for Multiple Clusters
  confluent.platform.kafka_connectors:
    connect_url: "http{% if hostvars[groups[item][0]].kafka_connect_ssl_enabled|default(kafka_connect_ssl_enabled) %}s{% endif %}://{{ hostvars[groups[item][0]]|confluent.platform.resolve_hostname }}:{{ hostvars[groups[item][0]].kafka_connect_rest_port|default(kafka_connect_rest_port) }}/connectors"
    active_connectors: "{{ hostvars[groups[item][0]].kafka_connect_connectors }}"
    timeout: "{{ kafka_connect_deploy_connector_timeout }}"
    username: "{% if rbac_enabled %}{{kafka_connect_ldap_user}}{% else %}{{none}}{% endif %}"
    password: "{% if rbac_enabled %}{{kafka_connect_ldap_password}}{% else %}{{none}}{% endif %}"
    client_cert: "{% if (ssl_provided_keystore_and_truststore and ssl_mutual_auth_enabled) %}{{kafka_connect_cert_path}}{% elif ssl_mutual_auth_enabled %}{{certs_chain}}{% else %}{{none}}{% endif %}"
    client_key: "{% if ssl_mutual_auth_enabled %}{{kafka_connect_key_path}}{% else %}{{none}}{% endif %}"
  when: hostvars[groups[item][0]].kafka_connect_connectors is defined
  delegate_to: "{{ groups[item][0] }}"
  loop: "{{subgroups}}"
  run_once: true
