---
- name: Grant Connect User ResourceOwner on Connector Topics
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{kafka_connect_ldap_user}}/roles/ResourceOwner/bindings"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}"
            }
        },
        "resourcePatterns": [
          {
            "resourceType":"Topic",
            "name":"{{item.config.topics}}",
            "patternType":"LITERAL"
          }
        ]
      }
    status_code: 204
  register: connect_mds_result
  until: connect_mds_result.status == 204
  retries: "{{ mds_retries }}"
  delay: 5
  loop: "{{kafka_connect_connectors}}"

- name: Grant Connect User ResourceOwner on Connector Subject
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{kafka_connect_ldap_user}}/roles/ResourceOwner/bindings"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}",
            "schema-registry-cluster": "schema-registry"
            }
        },
        "resourcePatterns": [
          {
            "resourceType":"Subject",
            "name":"{{item.config.topics}}-value",
            "patternType":"LITERAL"
          }
        ]
      }
    status_code: 204
  register: connect_mds_result
  until: connect_mds_result.status == 204
  retries: "{{ mds_retries }}"
  delay: 5
  loop: "{{kafka_connect_connectors}}"

- name: Grant Connect User DeveloperRead role to Consumer group
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{kafka_connect_ldap_user}}/roles/DeveloperRead/bindings"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}"
            }
        },
        "resourcePatterns": [
          {
            "resourceType":"Group",
            "name":"connect-",
            "patternType":"PREFIXED"
          }
        ]
      }
    status_code: 204
  register: connect_mds_result
  until: connect_mds_result.status == 204
  retries: "{{ mds_retries }}"
  delay: 5

- name: Grant Connect User ResourceOwner for the Connector
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{kafka_connect_ldap_user}}/roles/ResourceOwner/bindings"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}",
            "connect-cluster": "{{kafka_connect_final_properties['group.id']}}"
            }
        },
        "resourcePatterns": [
          {
            "resourceType":"Connector",
            "name":"{{item.name}}",
            "patternType":"LITERAL"
          }
        ]
      }
    status_code: 204
  register: connect_mds_result
  until: connect_mds_result.status == 204
  retries: "{{ mds_retries }}"
  delay: 5
  loop: "{{kafka_connect_connectors}}"
