- hosts: ssl_CA
  vars:
    - confluent_roles:
        - ssl_CA
  tasks:
  - import_role:
      name: cp-ansible
    tags:
      - pre-install

- hosts: zookeeper
  vars:
    - confluent_roles:
        - zookeeper
  tasks:
  - import_role:
      name: cp-ansible

- hosts: broker
  vars:
    - confluent_roles:
        - kafka-broker
  tasks:
  - import_role:
      name: cp-ansible

- hosts: schema-registry
  vars:
    - confluent_roles:
        - schema-registry
  tasks:
  - import_role:
      name: cp-ansible

- hosts: connect-distributed
  vars:
    - confluent_roles:
        - connect-distributed
  tasks:
  - import_role:
      name: cp-ansible

- hosts: control-center
  vars:
    - confluent_roles:
        - control-center
  tasks:
  - import_role:
      name: cp-ansible

- hosts: kafka-rest
  vars:
    - confluent_roles:
        - kafka-rest
  tasks:
  - import_role:
      name: cp-ansible

- hosts: ksql
  vars:
    - confluent_roles:
        - ksq
  tasks:
  - import_role:
      name: cp-ansible

- hosts: tools
  vars:
    - confluent_roles:
        - tools
  tasks:
  - import_role:
      name: cp-ansible
    tags:
      - post-install
