---
### Installation of Confluent Community Edition on CentOS7.
### SASL OAUTHBEARER Auth.

driver:
  name: docker
platforms:
  - name: zookeeper1
    hostname: zookeeper1.confluent
    groups:
      - zookeeper
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-broker1
    hostname: kafka-broker1.confluent
    groups:
      - kafka_broker
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
provisioner:
  inventory:
    group_vars:
      all:
        confluent_server_enabled: false
        sasl_protocol: plain
        kafka_broker_custom_listeners:
          broker:
            name: BROKER
            port: 9091
            sasl_protocol: plain
          internal:
            name: INTERNAL
            port: 9092
            sasl_protocol: plain
          ob:
            name: OB
            port: 9096
            sasl_protocol: oauthbearer
        kafka_broker_custom_properties:
          listener.name.ob.oauthbearer.sasl.jaas.config: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
