---
### Validates that SASL OAUTHBEARER protocol is set.
### Validates that properties for callback handlers are not set.

- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: listener.name.ob.sasl.enabled.mechanisms
        expected_value: OAUTHBEARER
    - import_role:
        name: confluent.test
        tasks_from: check_property_unset.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: listener.name.ob.oauthbearer.sasl.login.callback.handler.class
    - import_role:
        name: confluent.test
        tasks_from: check_property_unset.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: listener.name.ob.oauthbearer.sasl.server.callback.handler.class
