---
- name: Add an Apt signing key
  apt_key:
    url: "{{ repository.key }}"
    state: present
  become: yes

- name: Add apt Repository
  apt_repository:
    repo: "{{ repository.url }}"
    state: present
  become: yes
