- name: Add an Apt signing key
  apt_key:
    url: "http://packages.confluent.io/deb/{{ confluent.version.major }}.{{ confluent.version.minor }}/archive.key"
    state: present
  become: yes

- name: Add apt Repository
  apt_repository:
    repo: "deb http://packages.confluent.io/deb/{{ confluent.version.major }}.{{ confluent.version.minor }} stable main"
    state: present
  become: yes
