---
# TODO By using the http protocol var, you dont need two conditional tasks here
# do this in the other roles, plus make test case
- name: Wait for API to return 200
  uri:
    url: "{{ksql_http_protocol}}://localhost:{{ksql_listener_port}}/info"
    status_code: 200
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
