---
- name: Verify Package Version
  hosts: all
  gather_facts: false
  vars:
    latest_version: 5.4.1
  tasks:
    - import_role:
        name: confluent.variables_handlers

    - shell: "rpm -qa | grep confluent | grep {{latest_version}}"
      register: package_grep
      failed_when: "package_grep.rc == 0"
      when: confluent_package_version != latest_version

- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: confluent.metrics.reporter.security.protocol
        expected_value: PLAINTEXT

- name: Verify - schema_registry
  hosts: schema_registry
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/schema-registry/schema-registry.properties
        property: kafkastore.security.protocol
        expected_value: PLAINTEXT

- name: Verify - kafka_rest
  hosts: kafka_rest
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka-rest/kafka-rest.properties
        property: client.security.protocol
        expected_value: PLAINTEXT

- name: Verify - kafka_connect
  hosts: kafka_connect
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/connect-distributed.properties
        property: security.protocol
        expected_value: PLAINTEXT

- name: Verify - ksql
  hosts: ksql
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/ksql/ksql-server.properties
        property: security.protocol
        expected_value: PLAINTEXT

- name: Verify - control_center
  hosts: control_center
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.streams.security.protocol
        expected_value: PLAINTEXT

- name: Verify - Zookeeper User Change
  hosts: zookeeper1-kafka-broker1
  gather_facts: false
  tasks:
    - name: Set Zookeeper user to new user
      set_fact:
        zookeeper_user: zk-test

    - name: Set Zookeeper Group
      set_fact:
        zookeeper_group: confluent

    - name: Create Zookeeper User
      user:
        name: "{{zookeeper_user}}"
        comment: "Zookeeper User"
        system: true
        group: "{{zookeeper_group}}"

    - name: Create Log Directory
      file:
        path: "{{zookeeper.log_path}}"
        state: directory
        group: "{{zookeeper_group}}"
        owner: "{{zookeeper_user}}"
        mode: 0770

    - name: Restart Service
      systemd:
        daemon_reload: true
        name: "{{zookeeper_service_name}}"
        state: restarted

    - import_role:
        name: confluent.zookeeper
        tasks_from: health_check.yml

    - name: Restart Service
      systemd:
        daemon_reload: true
        name: "{{kafka_broker_service_name}}"
        state: restarted

    - name: Wait for Under Replicated Partitions on Broker
      include_tasks: ../../../../tasks/wait_for_urp.yml
