schema:
  registry:
    user: cp-schema-registry
    group: cp-schema-registry
    config_file: /etc/kafka/schema-registry.properties
    service_name: confluent-schema-registry
    config:
      listeners: http://0.0.0.0:8081
      kafkastore.topic: _schemas
      debug: false
    environment:
      SCHEMA_REGISTRY_HEAP_OPTS: "-Xmx1000M"
      LOG_DIR: /var/log/schema-registry
    systemd:
      enabled: yes
      state: started
