---
driver:
  name: docker
platforms:
  - name: zookeeper1
    hostname: zookeeper1
    groups:
      - zookeeper
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
    exposed_ports:
      - 2181
      - 2888
      - 3888
    # published_ports:
    #   - 2181:2181
    #   - 2888:2888
    #   - 3888:3888
    pre_build_image: true
  - name: zookeeper2
    hostname: zookeeper2
    groups:
      - zookeeper
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
    exposed_ports:
      - 2181
      - 2888
      - 3888
    # published_ports:
    #   - 2181:2181
    #   - 2888:2888
    #   - 3888:3888
    pre_build_image: true
  # - name: ubuntu1604
  # pip3 install testinfra==3.0.5 molecule ansible docker selinux -i https://nexus3.onap.org/repository/PyPi/simpl
  #   image: geerlingguy/docker-ubuntu1604-ansible
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   pre_build_image: true
  # - name: debian9
  #   image: geerlingguy/docker-debian9-ansible
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  playbooks:
    converge: ../converge.yml
verifier:
  name: ansible
