---
driver:
  name: docker
platforms:
  - name: zookeeper1
    hostname: zookeeper1
    groups:
      - zookeeper
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
    # pre_build_image: true
  - name: zookeeper2
    hostname: zookeeper2
    groups:
      - zookeeper
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
    # pre_build_image: true
  - name: zookeeper3
    hostname: zookeeper3
    groups:
      - zookeeper
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
    # pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  # group_vars:
  #   all:
  #     ansible_python_interpreter: /usr/bin/python
  playbooks:
    converge: ../converge.yml
verifier:
  name: ansible
