---
- name: Verify
  hosts: zookeeper
  tasks:
    - name: Get Stats on override.conf
      stat:
        path: /etc/systemd/system/confluent-zookeeper.service.d/override.conf
      register: override_conf

    - name: Assert ownership on override.conf
      assert:
        that:
          - override_conf.stat.gr_name == "confluent"
          - override_conf.stat.pw_name == "cp-kafka"
        quiet: yes

    - name: Check custom property configured
      shell: grep -Fxq "syncLimit=3" /etc/kafka/zookeeper.properties
      register: checkprop
      check_mode: no
      changed_when: no
      failed_when: checkprop.rc != 0

    - name: Check three zk nodes
      shell: grep "server." /etc/kafka/zookeeper.properties | wc -l
      register: checknodes
      check_mode: no
      changed_when: no
      failed_when: checknodes.stdout|int != 3
