ksql_listener_port: 8088
ksql_config_default:
  application.id: ksql-server
  listeners: http://0.0.0.0:{{ksql_listener_port}}
  ssl.endpoint.identification.algorithm: ""
  bootstrap.servers: "{{ client.broker.bootstrap_servers }}"
  ksql.schema.registry.url: "{{ client.schema.registry.urls }}"
ksql:
  config_file: /etc/ksql/ksql-server.properties
  service_name: confluent-ksql
  systemd_override: /etc/systemd/system/confluent-ksql.service.d
  user: cp-ksql
  group: confluent
  environment:
    KSQL_HEAP_OPTS: "-Xmx3g"
  config: "{{ client_config | append_prefix(['consumer.', 'producer.']) | combine(ksql_config_default) }}"
  systemd:
    enabled: yes
    state: started
