- name: connect distributed create config
  template:
    src: connect-distributed.properties.j2
    dest: "{{kafka.connect.distributed.config_file}}"
    mode: 0640
    owner: "{{kafka.connect.user}}"
    group: "{{kafka.connect.group}}"
  notify:
    - restart connect distributed
- name: connect distributed configure service
  systemd:
    name: "{{kafka.connect.distributed.service_name}}"
    enabled: "{{kafka.connect.distributed.systemd.enabled}}"
    state: "{{kafka.connect.distributed.systemd.state}}"    
