---
driver:
  name: docker
platforms:
  - name: zookeeper1
    hostname: zookeeper1
    groups:
      - zookeeper
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../../../confluent.control_center/molecule/Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: zookeeper2
    hostname: zookeeper2
    groups:
      - zookeeper
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../../../confluent.control_center/molecule/Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: zookeeper3
    hostname: zookeeper3
    groups:
      - zookeeper
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../../../confluent.control_center/molecule/Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  inventory:
    group_vars:
      all:
        zookeeper_user: custom-kafka
        zookeeper_group: custom
  playbooks:
    converge: ../converge.yml
verifier:
  name: ansible
