---
- name: Verify
  hosts: zookeeper
  tasks:
    - name: Get Stats on override.conf
      stat:
        path: /etc/systemd/system/confluent-zookeeper.service.d/override.conf
      register: override_conf

    - name: Get Stats on zookeeper.properties
      stat:
        path: /etc/kafka/zookeeper.properties
      register: zookeeper_properties

    - name: Assert ownership on files
      assert:
        that:
          - override_conf.stat.gr_name == "custom"
          - override_conf.stat.pw_name == "custom-kafka"
          - zookeeper_properties.stat.gr_name == "custom"
          - zookeeper_properties.stat.pw_name == "custom-kafka"
        quiet: yes
