confluent:
  control:
    center:
      user: cp-control-center
      group: cp-control-center
      config_file: /etc/confluent-control-center/control-center.properties
      service_name: confluent-control-center
      config:
        confluent.controlcenter.streams.num.stream.threads: 8
      systemd:
        enabled: yes
        state: started
