- hosts: zookeeper
  tasks:
  - import_role:
      name: zookeeper
- hosts: broker
  tasks:
  - import_role:
      name: kafka-broker
- hosts: schema-registry
  tasks:
  - import_role:
      name: schema-registry
- hosts: connect-distributed
  tasks:
  - import_role:
      name: connect-distributed
- hosts: control-center
  tasks:
  - import_role:
      name: control-center
- hosts: kafka-rest
  tasks:
  - import_role:
      name: kafka-rest
- hosts: ksql
  tasks:
  - import_role:
      name: ksql
