kafkarest:
  user: cp-kafka-rest
  group: cp-kafka-rest
  config_file: /etc/kafka/kafka-rest.properties
  systemd_file: /usr/lib/systemd/system/confluent-kafka-rest.service
  service_name: confluent-kafka-rest
  config:
    listeners: http://0.0.0.0:8082
  environment:
    LOG_DIR: /var/log/kafka-rest
  systemd:
    enabled: yes
    state: started
