# Task to Update Java and Keytool Alternatives according to custom Java path

- name: Java Update Alternatives
  alternatives:
    name: java
    link: /usr/bin/java
    path: "{{custom_java_path}}/bin/java"
    priority: 1
  when: custom_java_path | length > 0

- name: Keytool Update Alternatives
  alternatives:
    name: keytool
    link: /usr/bin/keytool
    path: "{{custom_java_path}}/bin/keytool"
    priority: 1
  when: custom_java_path | length > 0
