---
- name: get java path
  shell: dirname $(dirname $(readlink -f $(which java)))
  register: java_path

- name: Disable JVM level FIPS
  lineinfile:
    path: "{{java_path.stdout}}/conf/security/java.security"
    search_string: 'security.useSystemPropertiesFile=true'
    line: security.useSystemPropertiesFile=false
    owner: root
    group: root
    mode: '0644'

- name: Configure crypto policies on Local Host
  shell: update-crypto-policies --set FIPS
  delegate_to: localhost
  become: true

- name: Configure crypto policies on Remote Host
  shell: update-crypto-policies --set FIPS
  become: true
