---
- name: Add Confluent Repo file
  template:
    src: confluent.repo.j2
    dest: /etc/yum.repos.d/confluent.repo
    mode: 0644
  register: confluent_repo_result
  until: confluent_repo_result is success
  retries: 5
  delay: 90
  when:
    - repository_configuration == 'confluent'
    - installation_method == "package"

- name: Add Custom Repo file
  copy:
    src: "{{custom_yum_repofile_filepath}}"
    dest: /etc/yum.repos.d/custom-confluent.repo
    mode: 0644
  register: custom_repo_result
  until: custom_repo_result is success
  retries: 5
  delay: 90
  when: repository_configuration == 'custom'

# Not using handler because of https://github.com/ansible/ansible/issues/41313
- name: yum-clean-all
  command: yum clean all
  args:
    warn: false
  register: yum_clean_result
  until: yum_clean_result is success
  retries: 5
  delay: 90
  when: >
    confluent_repo_result.changed|default(False) or
    repository_configuration == 'custom'

- name: Custom Java Install
  include_tasks: custom_java_install.yml

- name: Install Java
  yum:
    name: "{{redhat_java_package_name}}"
    state: present
  register: java_install_result
  until: java_install_result is success
  retries: 10
  delay: 5
  when: install_java|bool
  tags: package

- name: Install OpenSSL and Unzip
  yum:
    name:
      - openssl
      - unzip
  tags: package

- name: Get Java Version
  shell: java -version
  register: version_output

- name: Print Java Version
  debug:
    msg: "Current Java Version is: {{version_output.stderr_lines[0]}}"

- set_fact:
    pip_package_name: "{{ 'python-pip' if ansible_python_version is match('2.*') else 'python3-pip' }}"
    pip_version: "{{ 'pip==20.3.4' if ansible_python_version is match('2.*') else 'pip' }}"

- name: Install pip
  yum:
    name:
      - "{{ pip_package_name }}"
    state: present
  become: true

- name: Upgrade pip
  ansible.builtin.pip:
    name: "{{ pip_version }}"
    extra_args: --upgrade

- name: Install cryptography
  ansible.builtin.pip:
    name: cryptography
