---
- name: Delete SSL Certificate Generation Directory
  file:
    path: /var/ssl/private/generation
    state: absent

- name: Delete Old Keystore
  file:
    path: "{{keystore_path}}"
    state: absent

- name: Delete Old Truststore
  file:
    path: "{{truststore_path}}"
    state: absent

- name: Create SSL Certificate Generation Directory
  file:
    path: /var/ssl/private/generation
    state: directory
    mode: 0755

- name: Create Keystore and Truststore with Self Signed Certs
  include_tasks: self_signed_certs.yml
  when: self_signed|bool

- name: Create Keystore and Truststore with Custom Certs
  include_tasks: custom_certs.yml
  when: ssl_custom_certs|bool

- name: Copy Provided Keystore and Truststore to Host
  include_tasks: provided_keystore_and_truststore.yml
  when: ssl_provided_keystore_and_truststore|bool

- name: Delete SSL Certificate Generation Directory
  file:
    path: /var/ssl/private/generation
    state: absent
  when: delete_generation_dir|bool

- set_fact:
    user: "{{kafka_broker.user}}"
    group: "{{kafka_broker.group}}"
  when: service_name == 'kafka_broker'

- set_fact:
    user: "{{schema_registry.user}}"
    group: "{{schema_registry.group}}"
  when: service_name == 'schema_registry'

- set_fact:
    user: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  when: service_name == 'kafka_rest'

- set_fact:
    user: "{{kafka_connect.user}}"
    group: "{{kafka_connect.group}}"
  when: service_name == 'kafka_connect'

- set_fact:
    user: "{{ksql.user}}"
    group: "{{ksql.group}}"
  when: service_name == 'ksql'

- set_fact:
    user: "{{control_center.user}}"
    group: "{{control_center.group}}"
  when: service_name == 'control_center'

- name: Set Truststore and Keystore File Permissions
  file:
    path: "{{item}}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: '0644'
  loop:
    - "{{keystore_path}}"
    - "{{truststore_path}}"

- set_fact:
    certs_updated: true
