---
driver:
  name: docker
platforms:
  - name: zookeeper1
    hostname: zookeeper1
    groups:
      - zookeeper
    image: geerlingguy/docker-centos7-ansible
    dockerfile: Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka_broker1
    hostname: kafka_broker1
    groups:
      - kafka_broker
    image: geerlingguy/docker-centos7-ansible
    dockerfile: Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka_broker2
    hostname: kafka_broker2
    groups:
      - kafka_broker
    image: geerlingguy/docker-centos7-ansible
    dockerfile: Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka_broker3
    hostname: kafka_broker3
    groups:
      - kafka_broker
    image: geerlingguy/docker-centos7-ansible
    dockerfile: Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: schema_registry1
    hostname: schema_registry1
    groups:
      - schema_registry
    image: geerlingguy/docker-centos7-ansible
    dockerfile: Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka_connect1
    hostname: kafka_connect1
    groups:
      - kafka_connect
      - elastic
    image: geerlingguy/docker-centos7-ansible
    dockerfile: Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka_connect2
    hostname: kafka_connect2
    groups:
      - kafka_connect
      - syslog
    image: geerlingguy/docker-centos7-ansible
    dockerfile: Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: ksql1
    hostname: ksql1
    groups:
      - ksql
      - ksql1
    image: geerlingguy/docker-centos7-ansible
    dockerfile: Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: ksql2
    hostname: ksql2
    groups:
      - ksql
      - ksql2
    image: geerlingguy/docker-centos7-ansible
    dockerfile: Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: control_center1
    hostname: control_center1
    groups:
      - control_center
    image: geerlingguy/docker-centos7-ansible
    dockerfile: Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    published_ports:
      - "9021:9021"
    networks:
      - name: confluent
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  inventory:
    group_vars:
      ksql1:
        ksql_service_id: ksql1_
      ksql2:
        ksql_service_id: ksql2_
      elastic:
        kafka_connect_group_id: connect-elastic
      syslog:
        kafka_connect_group_id: connect_syslog
      control_center:
        ksql_cluster_ansible_group_names:
          - ksql1
          - ksql2
        kafka_connect_cluster_ansible_group_names:
          - syslog
          - elastic
  # playbooks:
  #   prepare: ../prepare.yml
  #   converge: ../converge.yml
verifier:
  name: ansible
