---
- name: Zookeeper Provisioning
  hosts: zookeeper
  tasks:
    - include_role:
        name: confluent.zookeeper

- name: Kafka Broker Provisioning
  hosts: kafka_broker
  tasks:
    - include_role:
        name: confluent.kafka_broker

- name: Schema Registry Provisioning
  hosts: schema_registry
  tasks:
    - include_role:
        name: confluent.schema_registry

- name: Kafka Connect Provisioning
  hosts: kafka_connect
  tasks:
    - include_role:
        name: confluent.kafka_connect

- name: KSQL Provisioning
  hosts: ksql
  tasks:
    - include_role:
        name: confluent.ksql
