---
- name: Verify
  hosts: control_center
  tasks:
    - name: Get Stats on override.conf
      stat:
        path: /etc/systemd/system/confluent-control-center.service.d/override.conf
      register: override_conf

    - name: Assert ownership on override.conf
      assert:
        that:
          - override_conf.stat.gr_name == "confluent"
          - override_conf.stat.pw_name == "cp-control-center"
        quiet: yes

    - name: Check multi connect config
      shell: grep -Fxq "confluent.controlcenter.connect.connect-elastic.cluster=http://kafka-connect1:8083" /etc/confluent-control-center/control-center-production.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

    - name: Check multi ksql config
      shell: grep -Fxq "confluent.controlcenter.ksql.ksql_cluster1.url=http://ksql1:8088" /etc/confluent-control-center/control-center-production.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0
