---
- name: Verify
  hosts: control_center
  tasks:
    - name: Get Stats on override.conf
      stat:
        path: /etc/systemd/system/confluent-control-center.service.d/override.conf
      register: override_conf

    - name: Assert ownership on override.conf
      assert:
        that:
          - override_conf.stat.gr_name == "confluent"
          - override_conf.stat.pw_name == "cp-control-center"
        quiet: yes
