- name: define default sasl users list
  set_fact:
    sasl_scram_users: "{{ sasl_scram_users | combine({ item.key: default_sasl_scram_users[item.key] }) }}"
  with_dict: "{{ kafka_broker_required_sasl_scram_users }}"
  when: item.value

- name: add custom sasl users
  set_fact:
    sasl_scram_users: "{{ sasl_scram_users | combine(kafka_broker_custom_sasl_scram_users) }}"
  when: kafka_broker_custom_sasl_scram_users is defined

- name: define default plain users list
  set_fact:
    sasl_plain_users: "{{ sasl_plain_users | combine({ item.key: default_sasl_plain_users[item.key] }) }}"
  with_dict: "{{ kafka_broker_required_sasl_plain_users }}"
  when: item.value

- name: add custom plain users
  set_fact:
    sasl_plain_users: "{{ sasl_plain_users | combine(kafka_broker_custom_sasl_plain_users) }}"
  when: kafka_broker_custom_sasl_plain_users is defined
