---
### Installation of Confluent Platform on CentOS8.
### MTLS enabled.
### Existing keystore and truststore located on all remote hosts.

driver:
  name: docker
platforms:
  - name: zookeeper1
    hostname: zookeeper1.confluent
    groups:
      - zookeeper
    image: geerlingguy/docker-centos8-ansible
    dockerfile: ../Dockerfile-rhel-base.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-broker1
    hostname: kafka-broker1.confluent
    groups:
      - kafka_broker
    image: geerlingguy/docker-centos8-ansible
    dockerfile: ../Dockerfile-rhel-base.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: schema-registry1
    hostname: schema-registry1.confluent
    groups:
      - schema_registry
    image: geerlingguy/docker-centos8-ansible
    dockerfile: ../Dockerfile-rhel-base.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-rest1
    hostname: kafka-rest1.confluent
    groups:
      - kafka_rest
    image: geerlingguy/docker-centos8-ansible
    dockerfile: ../Dockerfile-rhel-base.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-connect1
    hostname: kafka-connect1.confluent
    groups:
      - kafka_connect
    image: geerlingguy/docker-centos8-ansible
    dockerfile: ../Dockerfile-rhel-base.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: ksql1
    hostname: ksql1.confluent
    groups:
      - ksql
    image: geerlingguy/docker-centos8-ansible
    dockerfile: ../Dockerfile-rhel-base.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: control-center1
    hostname: control-center1.confluent
    groups:
      - control_center
    image: geerlingguy/docker-centos8-ansible
    dockerfile: ../Dockerfile-rhel-base.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    published_ports:
      - "9021:9021"
    networks:
      - name: confluent
provisioner:
  inventory:
    group_vars:
      all:

        ssl_enabled: true
        ssl_mutual_auth_enabled: true
        ssl_provided_keystore_and_truststore: true
        ssl_provided_keystore_and_truststore_remote_src: true

        zookeeper:
          ssl_keystore_filepath: "/var/ssl/private/zookeeper.keystore.jks"
          ssl_keystore_key_password: keystorepass
          ssl_keystore_store_password: keystorepass
          ssl_truststore_filepath: "/var/ssl/private/zookeeper.truststore.jks"
          ssl_truststore_password: truststorepass
          ssl_truststore_ca_cert_alias: CARoot

        kafka_broker:
          ssl_keystore_filepath: "/var/ssl/private/kafka_broker.keystore.jks"
          ssl_keystore_key_password: keystorepass
          ssl_keystore_store_password: keystorepass
          ssl_truststore_filepath: "/var/ssl/private/kafka_broker.truststore.jks"
          ssl_truststore_password: truststorepass
          ssl_truststore_ca_cert_alias: CARoot

        schema_registry:
          ssl_keystore_filepath: "/var/ssl/private/schema_registry.keystore.jks"
          ssl_keystore_key_password: keystorepass
          ssl_keystore_store_password: keystorepass
          ssl_truststore_filepath: "/var/ssl/private/schema_registry.truststore.jks"
          ssl_truststore_password: truststorepass
          ssl_truststore_ca_cert_alias: CARoot

        kafka_rest:
          ssl_keystore_filepath: "/var/ssl/private/kafka_rest.keystore.jks"
          ssl_keystore_key_password: keystorepass
          ssl_keystore_store_password: keystorepass
          ssl_truststore_filepath: "/var/ssl/private/kafka_rest.truststore.jks"
          ssl_truststore_password: truststorepass
          ssl_truststore_ca_cert_alias: CARoot

        kafka_connect:
          ssl_keystore_filepath: "/var/ssl/private/kafka_connect.keystore.jks"
          ssl_keystore_key_password: keystorepass
          ssl_keystore_store_password: keystorepass
          ssl_truststore_filepath: "/var/ssl/private/kafka_connect.truststore.jks"
          ssl_truststore_password: truststorepass
          ssl_truststore_ca_cert_alias: CARoot
    
        ksql:
          ssl_keystore_filepath: "/var/ssl/private/ksql.keystore.jks"
          ssl_keystore_key_password: keystorepass
          ssl_keystore_store_password: keystorepass
          ssl_truststore_filepath: "/var/ssl/private/ksql.truststore.jks"
          ssl_truststore_password: truststorepass
          ssl_truststore_ca_cert_alias: CARoot

        control_center:
          ssl_keystore_filepath: "/var/ssl/private/control_center.keystore.jks"
          ssl_keystore_key_password: keystorepass
          ssl_keystore_store_password: keystorepass
          ssl_truststore_filepath: "/var/ssl/private/control_center.truststore.jks"
          ssl_truststore_password: truststorepass
          ssl_truststore_ca_cert_alias: CARoot