---
- name: Host Prerequisites
  hosts: zookeeper:kafka_broker:schema_registry:kafka_connect:ksql:control_center:kafka_rest:kafka_connect_replicator
  gather_facts: false
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: variables

    - name: Gather OS Facts
      setup:
        gather_subset:
          - '!all'
          - '!any'
          - user
          - os_family
          - hardware
      tags: always

    - name: Debug
      debug:
        msg:
          - "Base config path ---------------"
          - "{{ config_base_path }}"
          - "Base Config prefix ---------------"
          - "{{ config_prefix }}"
          - "Config prefixes ---------------"
          - "{{ zookeeper_config_prefix }}"
          - "{{ kafka_broker_config_prefix }}"
          - "{{ schema_registry_config_prefix }}"
          - "{{ kafka_connect_config_prefix }}"
          - "{{ kafka_connect_replicator_config_prefix }}"
          - "{{ ksql_config_prefix }}"
          - "{{ kafka_rest_config_prefix }}"
          - "{{ control_center_config_prefix }}"
          - "Config file paths ---------------"
          - "{{ zookeeper.config_file }}"
          - "{{ kafka_broker.config_file }}"
          - "{{ schema_registry.config_file }}"
          - "{{ kafka_connect.config_file }}"
          - "{{ kafka_connect_replicator.replication_config_file }}"
          - "{{ kafka_rest.config_file }}"
          - "{{ control_center.config_file }}"
          - "{{ ksql.config_file }}"
          - "Trials ----------------------"
          - "{{ ((config_base_path, ksql_config_prefix) | path_join , 'ksql-server.properties') | path_join }} - fix ?"
          - "{{ ('/etc/', '/abc') | join }}"
          - "{{ ('/etc', 'abc') | path_join }}"
          - "{{ ('/etc/', '/abc') | path_join }}"
          - "{{ ('/etc/pqr', '/etc/xyz/abc') | path_join }}"

    - name: Create Certificate Authority and Copy to Ansible Host
      include_tasks: tasks/certificate_authority.yml
      tags: certificate_authority
      run_once: true
      when: >
        create_mds_certs|bool or
        (self_signed|bool and
        (zookeeper_ssl_enabled|bool or
        kafka_broker_listeners | confluent.platform.ssl_required(ssl_enabled) or
        kafka_broker_rest_ssl_enabled|bool or
        schema_registry_ssl_enabled|bool or
        kafka_rest_ssl_enabled|bool or
        kafka_connect_ssl_enabled|bool or
        ksql_ssl_enabled|bool or
        control_center_ssl_enabled|bool))

    - import_role:
        name: common
      tags: common

- import_playbook: zookeeper.yml

- import_playbook: kafka_broker.yml

- import_playbook: schema_registry.yml

- import_playbook: kafka_connect.yml

- import_playbook: ksql.yml

- import_playbook: kafka_rest.yml

- import_playbook: control_center.yml

- import_playbook: kafka_connect_replicator.yml
