---
- name: Import all variables
  hosts: all
  tags: always
  tasks:
    - import_role:
        name: variables

- name: Zookeeper Validation
  hosts: zookeeper
  gather_facts: false
  tags: zookeeper
  tasks:
    - include_role:
        name: common
        tasks_from: host_validations.yml

- name: Kafka Broker Validation
  hosts: kafka_broker
  gather_facts: false
  tags: kafka_broker
  tasks:
    - include_role:
        name: common
        tasks_from: host_validations.yml

- name: Schema Registry Validation
  hosts: schema_registry
  gather_facts: false
  tags: schema_registry
  tasks:
    - include_role:
        name: common
        tasks_from: host_validations.yml

- name: Kafta Connect Validation
  hosts: kafka_connect
  gather_facts: false
  tags: kafka_connect
  tasks:
    - include_role:
        name: common
        tasks_from: host_validations.yml

- name: Kafta Connect Validation
  hosts: kafka_connect_replicator
  gather_facts: false
  tags: kafka_connect_replicator
  tasks:
    - include_role:
        name: common
        tasks_from: host_validations.yml

- name: KSQL Validation
  hosts: ksql
  gather_facts: false
  tags: ksql
  tasks:
    - include_role:
        name: common
        tasks_from: host_validations.yml

- name: Kafka Rest Validation
  hosts: kafka_rest
  gather_facts: false
  tags: kafka_rest
  tasks:
    - include_role:
        name: common
        tasks_from: host_validations.yml

- name: Control Center Validation
  hosts: control_center
  gather_facts: false
  tags: control_center
  tasks:
    - include_role:
        name: common
        tasks_from: host_validations.yml
