---
- import_playbook: kafka_controller.yml
  tags: DualWrite

- import_playbook: kafka_broker.yml
  vars:
    deployment_strategy: 'serial'
  tags: DualWrite

- name: Wait for migration to complete
  hosts: kafka_controller
  tags: DualWrite
  gather_facts: false
  tasks:
    - import_role:
        name: variables

    - name: Wait for Metadata Migration
      uri:
        url: "{{ 'https' if kafka_controller_jolokia_ssl_enabled|bool else 'http' }}://localhost:{{kafka_controller_jolokia_port}}/jolokia/read/kafka.controller:type=KafkaController,name=ZkMigrationState"
        validate_certs: false
        status_code: 200
      retries: 10
      delay: 90
      until: jolokia_output.json.value.Value == 1
      register: jolokia_output
      when: jolokia_auth_mode == "none"

    - name: Wait for Metadata Migration
      uri:
        url: "{{ 'https' if kafka_controller_jolokia_ssl_enabled|bool else 'http' }}://localhost:{{kafka_controller_jolokia_port}}/jolokia/read/kafka.controller:type=KafkaController,name=ZkMigrationState"
        validate_certs: false
        force_basic_auth: true
        url_username: "{{ jolokia_user }}"
        url_password: "{{ jolokia_password }}"
        status_code: 200
      retries: 10
      delay: 90
      until: jolokia_output.json.value.Value == 1
      register: jolokia_output
      when: jolokia_auth_mode == "basic"

- name: Migrate Brokers to Kraft
  hosts: kafka_broker
  tags: MigratetoKraft
  gather_facts: true
  tasks:
    - import_role:
        name: variables

    - name: Remove Zookeeper configs from Broker
      lineinfile:
        path: "{{ kafka_broker.config_file }}"
        state: absent
        regexp: "{{ item }}*"
      loop:
        - zookeeper
        - inter.broker.protocol.version

    - name: Reconfigure ZK Brokers as KRaft brokers
      lineinfile:
        path: "{{ kafka_broker.config_file }}"
        line: process.roles=broker

- name: Restart Kafka Broker
  hosts: kafka_broker
  tags: MigratetoKraft
  gather_facts: true
  serial: '1'
  tasks:
    - include_role:
        name: kafka_broker
        tasks_from: restart_and_wait.yml
    - include_role:
        name: kafka_broker
        tasks_from: health_check.yml
      tags: health_check

- name: Take Controllers out of migration mode
  hosts: kafka_controller
  tags: MigratetoKraft
  gather_facts: true
  tasks:
    - import_role:
        name: variables

    - name: Remove Zookeeper configs from Controller
      lineinfile:
        path: "{{ kafka_controller.config_file }}"
        state: absent
        regexp: "{{ item }}*"
      loop:
        - zookeeper

- name: Restart Kafka Controller
  hosts: kafka_controller
  tags: MigratetoKraft
  gather_facts: true
  serial: '1'
  tasks:
    - include_role:
        name: kafka_controller
        tasks_from: restart_and_wait.yml
    - include_role:
        name: kafka_controller
        tasks_from: health_check.yml
      tags: health_check

- name: Finish Migration
  hosts: kafka_controller
  tags: MigratetoKraft
  tasks:
    - debug:
        msg: "Migration from Zookeeper to Kraft has completed, you may shut down your Zookeeper."
