---
- name: Replace root logger
  replace:
    path: "{{log4j_file}}"
    regexp: 'log4j.rootLogger=.*'
    replace: "log4j.rootLogger={{log4j_root_logger}}"
  notify: "{{handler}}"
  when: log4j_root_logger is defined

- name: Replace DailyRollingFileAppender with RollingFileAppender
  replace:
    path: "{{log4j_file}}"
    regexp: '=org.apache.log4j.DailyRollingFileAppender'
    replace: '=org.apache.log4j.RollingFileAppender'
  notify: "{{handler}}"

- name: Remove Key log4j.appender.X.DatePattern
  lineinfile:
    path: "{{log4j_file}}"
    state: absent
    regexp: 'log4j.appender.*.DatePattern=.*'
  notify: "{{handler}}"

- name: Register Appenders
  shell: |
    grep RollingFileAppender {{log4j_file}} | cut -d '=' -f 1 | cut -d '.' -f 3
  register: appenders_grep
  changed_when: false

- name: Add Max Size Properties
  lineinfile:
    path: "{{log4j_file}}"
    insertafter: "log4j.appender.{{ item[0] }}=org.apache.log4j.RollingFileAppender"
    regexp: "log4j.appender.{{ item[0] }}.{{ item[1] }}"
    line: "log4j.appender.{{ item[0] }}.{{ item[1] }}"
  with_nested:
    - "{{appenders_grep.stdout_lines}}"
    - [ 'Append=true', 'MaxBackupIndex=10', 'MaxFileSize=100MB' ]
  notify: "{{handler}}"
