---
- name: Verify
  hosts: all
  tasks:
    - name: Get stats on jolokia jar
      stat:
        path: /opt/jolokia/jolokia.jar
      register: jolokia_jar

    - name: Get stats on prometheus jar
      stat:
        path: /opt/prometheus/jmx_prometheus_javaagent.jar
      register: prometheus_jar

    - name: Get stats on custom repofile
      stat:
        path: /etc/yum.repos.d/custom-confluent.repo
      register: custom_repofile

    - name: Assert files exist properly
      assert:
        that:
          - not jolokia_jar.stat.exists
          - prometheus_jar.stat.exists
          - custom_repofile.stat.exists
        quiet: yes
