---
- name: Verify
  hosts: all
  tasks:
    - name: Check if jolokia jar exists
      stat:
        path: /opt/jolokia/jolokia.jar
      register: jolokia_jar

    - name: Assert jolokia jar not downloaded
      assert:
        that: "jolokia_jar.stat.exists == False"

    - name: Check if prometheus jar exists
      stat:
        path: /opt/prometheus/jmx_prometheus_javaagent.jar
      register: prometheus_jar

    - name: Assert prometheus jar downloaded
      assert:
        that: "prometheus_jar.stat.exists == True"

    - name: Check if custom repofile exists
      stat:
        path: /etc/yum.repos.d/custom-confluent.repo
      register: custom_repofile

    - name: Assert custom repofile created
      assert:
        that: "custom_repofile.stat.exists == True"
