---
- name: Generate CA for Self Signed Certs
  hosts: zookeeper[0]
  tasks:
  - import_role:
      name: confluent.variables_handlers
  - name: Create Certificate Authority and Copy to Ansible Host
    include_tasks: ../../../../tasks/certificate_authority.yml
    when:
      - self_signed|bool
      - regenerate_ca|bool
      - ssl_enabled|bool
      
- name: Zookeeper Provisioning
  hosts: zookeeper
  tasks:
    - include_role:
        name: confluent.zookeeper

- name: Kafka Broker Provisioning
  hosts: kafka_broker
  tasks:
    - include_role:
        name: confluent.kafka_broker
