---
name: Lint Code Base
on: pull_request
jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Must validate all codebase to make ansible-lint work
          VALIDATE_ALL_CODEBASE: true
          LINTER_RULES_PATH: .
          VALIDATE_YAML: true
          YAML_CONFIG_FILE: .yamllint
          VALIDATE_ANSIBLE: true
          ANSIBLE_DIRECTORY: .
