- import_role:
    name: common
- name: connect create group
  group:
    name: "{{kafka.connect.group}}"
- name: control center create user
  user:
    name: "{{kafka.connect.user}}"
    comment: "Control Center User"
    system: yes
    group: "{{kafka.connect.group}}"